title: 唐镜博客天地
email: 1971419718@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Tang Jing # add your name
author-pic: ace.jpg
about-author:   My name is Tang Jing. I'm from Chongqing, China. Now I'm a new graduate programmer. Usually I like shopping, traveling, playing badminton, playing guitar, singing and dancing rap, but I don't like playing basketball very much. Welcome everyone to make friends, leather is very happy!My qq is 924987841.

# Contact links
email: 924987841@qq.com
phone: 13372624508
website: github.com/tangjiahao
serchsys: www.baidu.com # Add your Linkedin handle
github: tangjiahao?tab=repositories/ # Add your Github handle
taobao: www.taobao.com # Add your Twitter handle
wangyiyun: music.163.com/#/user/home?id=619534774 # Add your Facebook handle


# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 4
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
